# Nombre de la aplicación
spring.application.name=lab_datos
# Configuración de la BBDD H2 en memoria
spring.datasource.url=jdbc:h2:mem:lab_datos
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# Consola H2 para que los alumnos vean las tablas en el navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Mostrar el SQL que genera Hibernate en la terminal de VSC
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update